<?php

namespace OneSheet\Style;

/**
 * Class FontName holds constants for all fonts
 * with cell autosizing support.
 *
 * @package OneSheet
 */
class FontName
{
    const AHARONI_GRAS = 'Aharoni Gras';
    const ANDALUS = 'Andalus';
    const ANGSANAUPC = 'AngsanaUPC';
    const ANGSANAUPC_GRAS = 'AngsanaUPC Gras';
    const ANGSANA_NEW = 'Angsana New';
    const ANGSANA_NEW_GRAS = 'Angsana New Gras';
    const APARAJITA = 'Aparajita';
    const ARABIC_TYPESETTING = 'Arabic Typesetting';
    const ARIAL = 'Arial';
    const ARIAL_BLACK_NORMAL = 'Arial Black Normal';
    const ARIAL_GRAS = 'Arial Gras';
    const BROWALLIAUPC = 'BrowalliaUPC';
    const BROWALLIA_NEW = 'Browallia New';
    const CALIBRI = 'Calibri';
    const CALIBRI_LIGHT = 'Calibri Light';
    const CANDARA = 'Candara';
    const COMIC_SANS_MS = 'Comic Sans MS';
    const COMIC_SANS_MS_GRAS = 'Comic Sans MS Gras';
    const CONSOLAS = 'Consolas';
    const CONSTANTIA = 'Constantia';
    const CORBEL = 'Corbel';
    const CORDIAUPC = 'CordiaUPC';
    const CORDIA_NEW = 'Cordia New';
    const COURIER_NEW = 'Courier New';
    const COURIER_NEW_GRAS = 'Courier New Gras';
    const DAUNPENH = 'DaunPenh';
    const DAVID = 'David';
    const DILLENIAUPC = 'DilleniaUPC';
    const DILLENIAUPC_GRAS = 'DilleniaUPC Gras';
    const DOKCHAMPA = 'DokChampa';
    const DROID_SANS = 'Droid Sans';
    const DROID_SANS_MONO = 'Droid Sans Mono';
    const DROID_SERIF = 'Droid Serif';
    const EBRIMA = 'Ebrima';
    const EBRIMA_GRAS = 'Ebrima Gras';
    const ESTRANGELO_EDESSA = 'Estrangelo Edessa';
    const EUCROSIAUPC = 'EucrosiaUPC';
    const EUCROSIAUPC_GRAS = 'EucrosiaUPC Gras';
    const EUPHEMIA = 'Euphemia';
    const FRANKLIN_GOTHIC_MEDIUM = 'Franklin Gothic Medium';
    const FRANKRUEHL = 'FrankRuehl';
    const FREESIAUPC = 'FreesiaUPC';
    const GABRIOLA = 'Gabriola';
    const GAUTAMI = 'Gautami';
    const GEORGIA = 'Georgia';
    const GEORGIA_GRAS = 'Georgia Gras';
    const GISHA = 'Gisha';
    const GISHA_GRAS = 'Gisha Gras';
    const IMPACT = 'Impact';
    const IRISUPC = 'IrisUPC';
    const ISKOOLA_POTA = 'Iskoola Pota';
    const JASMINEUPC = 'JasmineUPC';
    const KALINGA = 'Kalinga';
    const KARTIKA = 'Kartika';
    const KHMER_UI = 'Khmer UI';
    const KHMER_UI_GRAS = 'Khmer UI Gras';
    const KODCHIANGUPC = 'KodchiangUPC';
    const KOKILA = 'Kokila';
    const LAO_UI = 'Lao UI';
    const LAO_UI_GRAS = 'Lao UI Gras';
    const LATHA = 'Latha';
    const LEELAWADEE = 'Leelawadee';
    const LEELAWADEE_GRAS = 'Leelawadee Gras';
    const LEVENIM_MT = 'Levenim MT';
    const LILYUPC = 'LilyUPC';
    const LUCIDA_CONSOLE = 'Lucida Console';
    const LUCIDA_SANS_UNICODE = 'Lucida Sans Unicode';
    const MANGAL = 'Mangal';
    const MICROSOFT_HIMALAYA = 'Microsoft Himalaya';
    const MICROSOFT_NEW_TAI_LUE = 'Microsoft New Tai Lue';
    const MICROSOFT_PHAGSPA = 'Microsoft PhagsPa';
    const MICROSOFT_SANS_SERIF = 'Microsoft Sans Serif';
    const MICROSOFT_TAI_LE = 'Microsoft Tai Le';
    const MICROSOFT_UIGHUR = 'Microsoft Uighur';
    const MICROSOFT_YI_BAITI = 'Microsoft Yi Baiti';
    const MIRIAM = 'Miriam';
    const MIRIAM_FIXED = 'Miriam Fixed';
    const MONACO = 'Monaco';
    const MONGOLIAN_BAITI = 'Mongolian Baiti';
    const MOOLBORAN = 'MoolBoran';
    const MV_BOLI = 'MV Boli';
    const NARKISIM = 'Narkisim';
    const NYALA = 'Nyala';
    const PALATINO_LINOTYPE = 'Palatino Linotype';
    const PALATINO_LINOTYPE_GRAS = 'Palatino Linotype Gras';
    const PLANTAGENET_CHEROKEE = 'Plantagenet Cherokee';
    const RAAVI = 'Raavi';
    const ROD = 'Rod';
    const SAKKAL_MAJALLA = 'Sakkal Majalla';
    const SAKKAL_MAJALLA_GRAS = 'Sakkal Majalla Gras';
    const SEGOE_PRINT = 'Segoe Print';
    const SEGOE_SCRIPT = 'Segoe Script';
    const SEGOE_UI = 'Segoe UI';
    const SEGOE_UI_GRAS = 'Segoe UI Gras';
    const SEGOE_UI_LIGHT = 'Segoe UI Light';
    const SEGOE_UI_SYMBOL = 'Segoe UI Symbol';
    const SHONAR_BANGLA = 'Shonar Bangla';
    const SHRUTI = 'Shruti';
    const SIMPLIFIED_ARABIC = 'Simplified Arabic';
    const SIMPLIFIED_ARABIC_FIXED = 'Simplified Arabic Fixed';
    const SYLFAEN = 'Sylfaen';
    const SYMBOL = 'Symbol';
    const TAHOMA = 'Tahoma';
    const TAHOMA_GRAS = 'Tahoma Gras';
    const TIMES_NEW_ROMAN = 'Times New Roman';
    const TIMES_NEW_ROMAN_GRAS = 'Times New Roman Gras';
    const TRADITIONAL_ARABIC = 'Traditional Arabic';
    const TREBUCHET_MS = 'Trebuchet MS';
    const TREBUCHET_MS_GRAS = 'Trebuchet MS Gras';
    const TUNGA = 'Tunga';
    const UTSAAH = 'Utsaah';
    const VANI = 'Vani';
    const VERDANA = 'Verdana';
    const VERDANA_GRAS = 'Verdana Gras';
    const VIJAYA = 'Vijaya';
    const VRINDA = 'Vrinda';
    const WEBDINGS = 'Webdings';
    const WINGDINGS = 'Wingdings';
}
