name: Run PHPUnit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        php-version: [ "7.3", "7.4", "8.0", "8.2", "8.3", "8.4" ]

    concurrency:
      group: phpunit-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: zip, mbstring, gd
          tools: composer

      - name: Check GD Extension was installed
        run: php -m | grep gd

      - name: Update Composer
        run: composer self-update

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit
